---
- name: Configure Linux VMs
  hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure jq is installed
      ansible.builtin.apt:
        name: jq
        state: present

    - name: Ensure htop is installed
      ansible.builtin.apt:
        name: htop
        state: present

    - name: Ensure Apache is installed
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Start Apache service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a welcome HTML page
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head><title>Welcome</title></head>
            <body><h1>Hello from EEsh kumar</h1></body>
          </html>

    - name: Open port 80 in UFW
      ansible.builtin.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow SSH (port 22) before enabling UFW
      ansible.builtin.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Enable UFW firewall
      ansible.builtin.ufw:
        state: enabled
        policy: allow
  roles:
    - profile-n01731657
    - user-n01731657
    - datadisk-n01731657
    - webserver-n01731657
