---
- name: Create primary partition 1 (4GB) for /part1
  community.general.parted:
    device: /dev/sdc
    number: 1
    state: present
    part_type: primary
    part_end: 4GB
  become: yes

- name: Create primary partition 2 with remaining space for /part2
  community.general.parted:
    device: /dev/sdc
    number: 2
    state: present
    part_type: primary
    part_start: 4GB
  become: yes

- name: Create ext4 filesystem on /dev/sdc1
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdc1
  become: yes

- name: Create ext4 filesystem on /dev/sdc2
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdc2
  become: yes

- name: Create mount point for /part1
  ansible.builtin.file:
    path: /part1
    state: directory
    mode: '0755'
  become: yes

- name: Create mount point for /part2
  ansible.builtin.file:
    path: /part2
    state: directory
    mode: '0755'
  become: yes

- name: Mount /dev/sdc1 to /part1
  ansible.posix.mount:
    path: /part1
    src: /dev/sdc1
    fstype: ext4
    state: mounted
  become: yes

- name: Mount /dev/sdc2 to /part2
  ansible.posix.mount:
    path: /part2
    src: /dev/sdc2
    fstype: ext4
    state: mounted
  become: yes

- name: Persist mounts in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ item }}"
    state: present
    create: yes
  loop:
    - "/dev/sdc1 /part1 ext4 defaults 0 0"
    - "/dev/sdc2 /part2 ext4 defaults 0 0"
  become: yes
